spring:
  application:
    name: taco-cloud
    
server:
  port: 8080

taco:
  orders:
    pageSize: 20

---
spring:
  config:
    activate.on-profile: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  
logging:
  level:
    tacoes: WARN